version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: js-gardener
    versions:
    - 2.0.185
    - 2.0.186
    - 3.0.0
  - dependency-name: babel-preset-latest-node
    versions:
    - 5.5.0
  - dependency-name: object-scan
    versions:
    - 13.9.3
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
